"""empty message

Revision ID: 472b08acf271
Revises: 0c349b66d91d
Create Date: 2021-01-30 16:28:16.569832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472b08acf271'
down_revision = '0c349b66d91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_items', sa.Column('labelled_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'data_items', 'users', ['labelled_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_items', type_='foreignkey')
    op.drop_column('data_items', 'labelled_by')
    # ### end Alembic commands ###
